### ISSUE TITLE
Include robust version of covariance estimation

### ISSUE THREAD

**Issue by tschm** [cvxgrp/cvxmarkowitz#5]
Use the idea by @stephenpboyd

**Comment by kasperjo** [comment]
I'm working on this. Almost done.

For the robust factor covariance I'm doing the following: 
adjust the risk**2 by adding the following term:
(factor_volatility_uncertainty @ \abs(factor_weights))**2 + (idiosyncratic_volatility_uncertainty**2)@(weights**2)
(This should be the robust adjustment for a factor model.)

Here 'factor_volatility_uncertainty' is \sqrt(kappa)*\Sigma_ii^{1/2} from the Boyd Kahn paper, where Sigma is the factor covariance matrix. Keeping it as factor_volatility_uncertainty allows us to respect DPP rules. 'idiosyncratic_volatility_uncertainty' is \sqrt(kappa)*D_ii^{1/2}, where D is the diagonal part of the factor covariance model.

I ran into an issue with parameters. If we keep the objective as risk, i.e., sigma rather than sigma**2, I couldn't get it to respect DPP rules. I'm not sure if it's possible to do robust covariance with a risk objective that respects DPP, due to the \abs(weights) that comes up when we robustify.

Anyway, for now I'm switching to risk**2 as the objective. I remember Stephen recommended avoiding this. But I couldn't find another solution that respects DPP. Please let me know if you have any suggestions. Otherwise, I think we can always "hide" this from the user! (Having risk**2 as the objective works with DPP.)

**Comment by kasperjo** [comment]
Introducing the new variable works out nicely! Thanks Philip!

**Comment by stephenpboyd** [comment]
I am certain we can find something that uses volatility and not variance as the risk, and works with DPP.  The parameters would be F*\Sigma_f^{1/2}. And D^{1/2}.

**Comment by kasperjo** [comment]
> I am certain we can find something that uses volatility and not variance as the risk, and works with DPP. The parameters would be F*\Sigma_f^{1/2}. And D^{1/2}.
> […](#)
> On Jun 28, 2023, at 7:01 PM, kasperjo ***@***.***> wrote: I'm working on this. Almost done. For the robust factor covariance I'm doing the following: adjust the risk2 by adding the following term: (factor_volatility_uncertainty @ \abs(factor_weights))2 + (idiosyncratic_volatility_uncertainty2)@(weights2) (This should be the robust adjustment for a factor model.) Here 'factor_volatility_uncertainty' is \sqrt(kappa)*\Sigma_ii^{1/2} from the Boyd Kahn paper, where Sigma is the factor covariance matrix. Keeping it as factor_volatility_uncertainty allows us to respect DPP rules. 'idiosyncratic_volatility_uncertainty' is \sqrt(kappa)*D_ii^{1/2}, where D is the diagonal part of the factor covariance model. I ran into an issue with parameters. If we keep the objective as risk, i.e., sigma rather than sigma**2, I couldn't get it to respect DPP rules. I'm not sure if it's possible to do robust covariance with a risk objective that respects DPP, due to the \abs(weights) that comes up when we robustify. Anyway, for now I'm switching to risk2 as the objective. I remember Stephen recommended avoiding this. But I couldn't find another solution that respects DPP. Please let me know if you have any suggestions. Otherwise, I think we can always "hide" this from the user! (Having risk2 as the objective works with DPP.) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Yes, it did work out!
